# Railway Nixpacks configuration for WolfAlert
[build]
# Use Python 3.11
nixPkgs = ["python311", "postgresql"]

[variables]
# Environment variables for build
PYTHONPATH = "/app"

[phases.setup]
# Install system dependencies
dependsOn = []
cmds = [
  "apt-get update",
  "apt-get install -y build-essential libpq-dev curl"
]

[phases.install]
# Install Python dependencies
dependsOn = ["setup"]
cmds = [
  "cd backend && pip install -r requirements.txt"
]

[phases.build]
# No specific build step needed for FastAPI
dependsOn = ["install"]

[start]
# Start command
cmd = "cd backend && uvicorn src.main:app --host 0.0.0.0 --port $PORT"